# Generated by Django 5.0.1 on 2024-02-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchuser',
            name='enter_the_vebinar',
            field=models.BooleanField(default=False),
        ),
    ]
