# Generated by Django 5.0.1 on 2024-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0002_catchuser_enter_the_vebinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
